import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const projectRoot = path.resolve(import.meta.dirname, '..');
const manifestPath = path.join(projectRoot, 'config/docs-manifest.json');
const outputRoot = path.join(projectRoot, 'src/content/docs');
const upstreamRoot = process.env.FINCH_DOCS_ROOT
  ? path.resolve(projectRoot, process.env.FINCH_DOCS_ROOT)
  : null;
const checkOnly = process.argv.includes('--check');
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
const routeBySource = new Map(manifest.map(({ source, destination }) => [source, `/${destination}/`]));

function yamlString(value) {
  return JSON.stringify(value);
}

async function readSource(source) {
  if (upstreamRoot) {
    return readFile(path.join(upstreamRoot, source), 'utf8');
  }

  const url = `https://raw.githubusercontent.com/darwin-finch/finch/main/${source}`;
  const response = await fetch(url, {
    headers: process.env.GITHUB_TOKEN
      ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
      : {},
  });
  if (!response.ok) {
    throw new Error(`Could not fetch ${source}: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

function sourcePath(from, target) {
  const [pathname, suffix = ''] = target.split(/(?=[?#])/u, 2);
  return {
    resolved: path.posix.normalize(path.posix.join(path.posix.dirname(from), pathname)),
    suffix,
  };
}

function rewriteLinks(markdown, source) {
  return markdown.replace(/(!?\[[^\]]*\])\(([^)]+)\)/gu, (whole, label, target) => {
    if (/^(?:[a-z]+:|#|\/)/iu.test(target)) return whole;

    const { resolved, suffix } = sourcePath(source, target);
    if (label.startsWith('!')) {
      return `${label}(https://raw.githubusercontent.com/darwin-finch/finch/main/${resolved}${suffix})`;
    }

    const internalRoute = routeBySource.get(resolved);
    if (internalRoute) return `${label}(${internalRoute}${suffix})`;
    return `${label}(https://github.com/darwin-finch/finch/blob/main/${resolved}${suffix})`;
  });
}

function renderDocument(entry, markdown) {
  const withoutTitle = markdown.replace(/^#\s+.+(?:\r?\n)+/u, '');
  const body = rewriteLinks(withoutTitle, entry.source)
    // Expressive Code does not bundle a Forth grammar. Plain text preserves
    // the source without emitting dozens of warnings during every build.
    .replace(/^```forth$/gmu, '```text')
    .trim();
  const sourceUrl = `https://github.com/darwin-finch/finch/blob/main/${entry.source}`;

  return `---
title: ${yamlString(entry.title)}
description: ${yamlString(entry.description)}
editUrl: ${yamlString(sourceUrl)}
sidebar:
  order: ${entry.order}
---

<!-- Generated by scripts/sync-docs.mjs from ${entry.source}. Do not edit. -->

> Canonical source: [\`${entry.source}\`](${sourceUrl}). This page is refreshed from the Finch repository when the website builds.

${body}
`;
}

const stale = [];
for (const entry of manifest) {
  const source = await readSource(entry.source);
  const rendered = renderDocument(entry, source);
  const output = path.join(outputRoot, `${entry.destination}.md`);

  if (checkOnly) {
    const existing = await readFile(output, 'utf8').catch(() => '');
    if (existing !== rendered) stale.push(entry.destination);
    continue;
  }

  await mkdir(path.dirname(output), { recursive: true });
  await writeFile(output, rendered);
}

if (stale.length > 0) {
  console.error(`Generated documentation is stale:\n${stale.map((item) => `- ${item}`).join('\n')}`);
  console.error('Run npm run sync-docs to refresh it.');
  process.exitCode = 1;
} else {
  console.log(checkOnly
    ? `Verified ${manifest.length} synchronized documentation pages.`
    : `Synchronized ${manifest.length} documentation pages.`);
}
